# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastmcp httpx aiofiles

# Copy project
COPY . /app

# Expose default port if any (fastmcp uses 3000 by default?)
# Not required for stdio communication

# Default command
CMD ["python", "main.py"]
